### ISSUE TITLE
Column names and values are mismatches

### ISSUE THREAD

**Issue by VijayalakshmiSundaravaradhan** [vasyas/binlog-triggers-mysql#2]
On "writerows" event, under the resulting "rows" section, the column names and their values are mismatched.

**Example:**
_Mismatched result_
```
    ID: 'Invalid',
    IsUploaded: 30,
    Result: <Buffer 00>
```

_Ideal result_
```
    ID: 30,
    IsUploaded: <Buffer 00>,
    Result: 'Invalid'
```

**Comment by vasyas** [comment]
This library is not generating binlog event objects by itself. Instead, it uses https://github.com/nevill/zongji to do that.
So I suggest filling this issue in Zongi's tracker.
